{% set name = "zarpaint" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zarpaint-{{ version }}.tar.gz
  sha256: f7bf37251575c248eb49136552c5b8fd299e8267aacc7ab3b24841dad8d24063

build:
  entry_points:
    - zarpaint = zarpaint._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - magicgui
    - napari >=0.4.18
    - numpy
    - python >=3.7
    - pyyaml
    - qtpy
    - scikit-image
    - scipy
    - toolz
    - zarr

test:
  imports:
    - zarpaint
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/zarpaint
  summary: Paint segmentations directly to on-disk/remote zarr arrays
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/jni/zarpaint

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jni
